on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n MayReg -g MayRegb832-rg --location "East US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n MayReg --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n MayReg --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n MayReg --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: mayreg.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "dockerfile" -t mayreg.azurecr.io/maycluster:${{ github.sha }}
        docker push mayreg.azurecr.io/maycluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_maycluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep maycluster8650 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace maycluster8650`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: maycluster8650
        container-registry-url: mayreg.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: mayclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: maycluster8650
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          mayreg.azurecr.io/maycluster:${{ github.sha }}
        imagepullsecrets: |
          mayclusterdockerauth